backend:
  name: github
  branch: master
  repo: ZediWards/GatsbyBlogTest

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  - name: "team"
    label: "Team"
    folder: "src/team"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Team Member", name: "title", widget: "string" }
      - { label: "Bio", name: "bio", widget: "markdown" }

  - name: "blog"
    label: "Blog"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
